coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/examples/**"
  - "**/docs/**"

comment:
  layout: "header, diff, files, sunburst"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

codecov:
  require_ci_to_pass: true 